version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
      nodejs: 10
  pre_build:
    commands:
      - cd frontend/
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      # copy the contents of /build to S3
      - aws s3 sync ./build $S3_BUCKETS
artifacts:
  files:
    - '**/*'
  base-directory: frontend/build